/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarPasswordRouteImport } from './routes/trocar-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedQuestoesIndexRouteImport } from './routes/_authenticated/questoes/index'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel/index'
import { Route as AuthenticatedHojeIndexRouteImport } from './routes/_authenticated/hoje/index'
import { Route as AuthenticatedGerarIndexRouteImport } from './routes/_authenticated/gerar/index'
import { Route as AuthenticatedEquipaIndexRouteImport } from './routes/_authenticated/equipa/index'
import { Route as AuthenticatedConstrutorIndexRouteImport } from './routes/_authenticated/construtor/index'
import { Route as AuthenticatedAtividadesIndexRouteImport } from './routes/_authenticated/atividades/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAjudaIndexRouteImport } from './routes/_authenticated/ajuda/index'

const TrocarPasswordRoute = TrocarPasswordRouteImport.update({
  id: '/trocar-password',
  path: '/trocar-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuestoesIndexRoute =
  AuthenticatedQuestoesIndexRouteImport.update({
    id: '/questoes/',
    path: '/questoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/painel/',
    path: '/painel/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHojeIndexRoute = AuthenticatedHojeIndexRouteImport.update({
  id: '/hoje/',
  path: '/hoje/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGerarIndexRoute = AuthenticatedGerarIndexRouteImport.update({
  id: '/gerar/',
  path: '/gerar/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipaIndexRoute =
  AuthenticatedEquipaIndexRouteImport.update({
    id: '/equipa/',
    path: '/equipa/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConstrutorIndexRoute =
  AuthenticatedConstrutorIndexRouteImport.update({
    id: '/construtor/',
    path: '/construtor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtividadesIndexRoute =
  AuthenticatedAtividadesIndexRouteImport.update({
    id: '/atividades/',
    path: '/atividades/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjudaIndexRoute = AuthenticatedAjudaIndexRouteImport.update({
  id: '/ajuda/',
  path: '/ajuda/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/trocar-password': typeof TrocarPasswordRoute
  '/ajuda/': typeof AuthenticatedAjudaIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/atividades/': typeof AuthenticatedAtividadesIndexRoute
  '/construtor/': typeof AuthenticatedConstrutorIndexRoute
  '/equipa/': typeof AuthenticatedEquipaIndexRoute
  '/gerar/': typeof AuthenticatedGerarIndexRoute
  '/hoje/': typeof AuthenticatedHojeIndexRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/questoes/': typeof AuthenticatedQuestoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/trocar-password': typeof TrocarPasswordRoute
  '/ajuda': typeof AuthenticatedAjudaIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/atividades': typeof AuthenticatedAtividadesIndexRoute
  '/construtor': typeof AuthenticatedConstrutorIndexRoute
  '/equipa': typeof AuthenticatedEquipaIndexRoute
  '/gerar': typeof AuthenticatedGerarIndexRoute
  '/hoje': typeof AuthenticatedHojeIndexRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/questoes': typeof AuthenticatedQuestoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/trocar-password': typeof TrocarPasswordRoute
  '/_authenticated/ajuda/': typeof AuthenticatedAjudaIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/atividades/': typeof AuthenticatedAtividadesIndexRoute
  '/_authenticated/construtor/': typeof AuthenticatedConstrutorIndexRoute
  '/_authenticated/equipa/': typeof AuthenticatedEquipaIndexRoute
  '/_authenticated/gerar/': typeof AuthenticatedGerarIndexRoute
  '/_authenticated/hoje/': typeof AuthenticatedHojeIndexRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/_authenticated/questoes/': typeof AuthenticatedQuestoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/trocar-password'
    | '/ajuda/'
    | '/app/'
    | '/atividades/'
    | '/construtor/'
    | '/equipa/'
    | '/gerar/'
    | '/hoje/'
    | '/painel/'
    | '/questoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/trocar-password'
    | '/ajuda'
    | '/app'
    | '/atividades'
    | '/construtor'
    | '/equipa'
    | '/gerar'
    | '/hoje'
    | '/painel'
    | '/questoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/trocar-password'
    | '/_authenticated/ajuda/'
    | '/_authenticated/app/'
    | '/_authenticated/atividades/'
    | '/_authenticated/construtor/'
    | '/_authenticated/equipa/'
    | '/_authenticated/gerar/'
    | '/_authenticated/hoje/'
    | '/_authenticated/painel/'
    | '/_authenticated/questoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TrocarPasswordRoute: typeof TrocarPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-password': {
      id: '/trocar-password'
      path: '/trocar-password'
      fullPath: '/trocar-password'
      preLoaderRoute: typeof TrocarPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/questoes/': {
      id: '/_authenticated/questoes/'
      path: '/questoes'
      fullPath: '/questoes/'
      preLoaderRoute: typeof AuthenticatedQuestoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hoje/': {
      id: '/_authenticated/hoje/'
      path: '/hoje'
      fullPath: '/hoje/'
      preLoaderRoute: typeof AuthenticatedHojeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerar/': {
      id: '/_authenticated/gerar/'
      path: '/gerar'
      fullPath: '/gerar/'
      preLoaderRoute: typeof AuthenticatedGerarIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipa/': {
      id: '/_authenticated/equipa/'
      path: '/equipa'
      fullPath: '/equipa/'
      preLoaderRoute: typeof AuthenticatedEquipaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/construtor/': {
      id: '/_authenticated/construtor/'
      path: '/construtor'
      fullPath: '/construtor/'
      preLoaderRoute: typeof AuthenticatedConstrutorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atividades/': {
      id: '/_authenticated/atividades/'
      path: '/atividades'
      fullPath: '/atividades/'
      preLoaderRoute: typeof AuthenticatedAtividadesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajuda/': {
      id: '/_authenticated/ajuda/'
      path: '/ajuda'
      fullPath: '/ajuda/'
      preLoaderRoute: typeof AuthenticatedAjudaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAjudaIndexRoute: typeof AuthenticatedAjudaIndexRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAtividadesIndexRoute: typeof AuthenticatedAtividadesIndexRoute
  AuthenticatedConstrutorIndexRoute: typeof AuthenticatedConstrutorIndexRoute
  AuthenticatedEquipaIndexRoute: typeof AuthenticatedEquipaIndexRoute
  AuthenticatedGerarIndexRoute: typeof AuthenticatedGerarIndexRoute
  AuthenticatedHojeIndexRoute: typeof AuthenticatedHojeIndexRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
  AuthenticatedQuestoesIndexRoute: typeof AuthenticatedQuestoesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAjudaIndexRoute: AuthenticatedAjudaIndexRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAtividadesIndexRoute: AuthenticatedAtividadesIndexRoute,
  AuthenticatedConstrutorIndexRoute: AuthenticatedConstrutorIndexRoute,
  AuthenticatedEquipaIndexRoute: AuthenticatedEquipaIndexRoute,
  AuthenticatedGerarIndexRoute: AuthenticatedGerarIndexRoute,
  AuthenticatedHojeIndexRoute: AuthenticatedHojeIndexRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
  AuthenticatedQuestoesIndexRoute: AuthenticatedQuestoesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TrocarPasswordRoute: TrocarPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
